name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Extract version from build.gradle.kts
      - name: Extract version
        id: extract_version
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[0-9.]+(?=")' app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # Add permission step before running Gradle
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Build the app
      - name: Build APK
        run: ./gradlew assembleRelease

      # Delete existing tag from remote (if it exists)
      - name: Delete existing tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ env.VERSION_NAME }}"; then
            git push --delete origin "v${{ env.VERSION_NAME }}"
          fi

      # Create and push the new tag
      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ env.VERSION_NAME }}" -m "Release v${{ env.VERSION_NAME }}"
          git push origin "v${{ env.VERSION_NAME }}"

      # Create a release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION_NAME }}"
          release_name: "v${{ env.VERSION_NAME }}"
          body: "Release version ${{ env.VERSION_NAME }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Determine APK path and name
      - name: Set APK file paths
        id: apk_paths
        run: |
          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            echo "APK_PATH=app/build/outputs/apk/release/app-release.apk" >> $GITHUB_ENV
            echo "APK_NAME=app-release-v${{ env.VERSION_NAME }}.apk" >> $GITHUB_ENV
          else
            echo "APK_PATH=app/build/outputs/apk/release/app-release-unsigned.apk" >> $GITHUB_ENV
            echo "APK_NAME=app-release-unsigned-v${{ env.VERSION_NAME }}.apk" >> $GITHUB_ENV
          fi

      # Upload APK to the release
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APK_PATH }}
          asset_name: ${{ env.APK_NAME }}
          asset_content_type: application/vnd.android.package-archive