name: Update version.json

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master # Ensure the master branch is checked out

      - name: Update version.json
        run: |
          echo "{
            \"version\": \"${{ github.event.release.tag_name }}\",
            \"url\": \"${{ github.event.release.html_url }}\"
          }" > version.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json to ${{ github.event.release.tag_name }}"
          git push origin master